---
- name: Tar the data directory
  archive:
    path:
      - /root/rally_home
    dest: "/rally-{{ inventory_hostname_short }}.tar.gz"

- name: Fetch rally data
  fetch:
    src: "/rally-{{ inventory_hostname_short }}.tar.gz"
    dest: "{{ backup_dir }}/rally-{{ inventory_hostname_short }}.tar.gz"
    flat: yes
  ignore_errors: True
