---
- name: Destroying MariaDB container
  docker_container:
    name: "mariadb-container"
    state: absent
    force_kill: yes
  tags: mariadb-d0

- name: Unmount /database-mariadb
  mount:
    path: /database-mariadb
    src: tmpfs
    fstype: tmpfs
    state: absent
  tags: mariadb-d1
