---
- name: Creating sbtest user for sysbench
  mysql_user:
    name: sbtest
    password: sbtest
    host: "%"
    login_user: root
    login_password: my-secret-pw
    login_host: "{{ hostname }}"
    priv: '*.*:ALL,GRANT'
  tags: sysbenchmaster-0

- name: Create MariaDB sbtest database for sysbench
  mysql_db:
    name: sbtest
    login_host: "{{ hostname }}"
    login_user: sbtest
    login_password: sbtest
    state: present
  tags: sysbenchmaster-1
