---
- name: Destroying CockroachDB container
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Unmount /database-cockroachdb
  mount:
    path: /database-cockroachdb
    src: tmpfs
    fstype: tmpfs
    state: absent

