# One of cockroachdb, mariadb, galera
database: mariadb

# Should we deployed the monitoring stack?
monitoring: false

g5k:
  # reservation: "2018-03-12 19:00:01"
  walltime: "02:00:00"
  dhcp: true
  job_name: juice-tests-docker
  env_name: debian9-x64-nfs-madpp
  resources:
    machines:
      - roles:
          - master
        cluster: ecotype
        nodes: 1
        primary_network: n1
        secondary_networks: []
      - roles:
          - madpp
        cluster: ecotype
        nodes: 1
        primary_network: n1
        secondary_networks: []
    networks:
      - id: n1
        roles:
          - control_network
          - database_network
        type: prod
        site: nantes
