---
- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-setuptools
    - libpq-dev
    # python-mysql for collectd
    - python-mysqldb
    - python-pip
  tags: python-0

- name: Install some python bindings
  pip:
    name: "{{ item }}"
  with_items:
    # version important because 3.0 doesn't work with current version of enoslib
    - docker==2.7.0
    - influxdb
    - psycopg2
    - flent
    - docker-py #test
  tags: python-1
