---
- name: Remove /sysbench directory
  file:
    path: /sysbench
    state: absent

- name: Destroying sysbench container
  docker_container:
    name: "sysbench"
    state: absent
    force_kill: yes
