---
- name: Install apt utils
  hosts: all
  roles:
    - { role: aptutils,
        tags: aptutils }

- name: Install pip libs
  hosts: all
  roles :
    - { role: piplibs,
        tags: piplibs }

- name: Install docker
  hosts: all
  roles:
    - { role: docker,
        tags: docker }

- name: Install registry
  hosts: registry
  roles:
    - { role: registry,
        tags: registry }

- name: MariaDB deployment
  hosts: database[0]
  roles:
    - { role: database,
        tags: mariadb }

- name: Sysbench deployment
  hosts: database
  roles:
    - { role: sysbench,
        tags: sysbench }

- name: Sysbench deployment
  hosts: database[0]
  roles:
    - { role: sysbenchmaster,
        tags: sysbenchmaster }
