- name: Starting the Docker registry
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    detach: true
    ports:
      - "{{ registry_port }}:5000"
    env:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
    volumes:
      - /mnt/registry:/registry:rw
  tags: registry-0

- name: Waiting for the registry service to become available
  wait_for:
    host: "{{ registry_ip }}"
    port: "{{ registry_port }}"
    state: started
    delay: 2
    timeout: 120
  tags: registry-1
