---
- name: Install some python bindings
  pip:
    name: "{{ item }}"
  with_items:
    # version important because 3.0 doesn't work with current version of enoslib
    - docker==2.7.0
    - influxdb
    - psycopg2
    - flent
  tags: piplibs-0
